#!/bin/bash

# prepare an AWS instance to run vector-store

set -e

dir=$(dirname ${BASH_SOURCE[0]})
dir=$(realpath $dir)

envs=$1
[[ -f $envs ]] || (echo envs file not provided ; exit 1)
source $envs

idx=$2
[[ -z $idx ]] && (echo idx not provided ; exit 1)

ip_ext=VS_IP_${idx}_EXT
ip_ext=${!ip_ext}

# copy ssh key
cat $LOCAL_SSH_PUB_KEY | ssh -i $AWS_SSH_KEY ubuntu@$ip_ext "cat >> /home/ubuntu/.ssh/authorized_keys"

# install docker and add ubuntu user to docker group
ssh ubuntu@$ip_ext bash <<EOF
set -e
sudo apt update
sudo apt install -y docker.io tmux
sudo usermod -a -G docker ubuntu
EOF

$dir/make-vs-os $envs $idx
