#!/bin/bash

set -e

envs=$1
[[ -f $envs ]] || (echo envs file not provided ; exit 1)
source $envs

idx=$2
[[ -z $idx ]] && (echo idx not provided ; exit 1)

ip_ext=VS_IP_${idx}_EXT
ip_ext=${!ip_ext}

ssh ubuntu@$ip_ext docker run -d \
    --name node-exporter \
    --net host \
    --pid host \
    -v /:/host:ro,rslave \
    $NODE_EXPORTER_DOCKER_IMAGE \
        --path.rootfs /host
