#!/bin/bash

# The script runs a vector-store node in an AWS instance.

set -e

envs=$1
[[ -f $envs ]] || (echo envs file not provided ; exit 1)
source $envs

idx=$2
[[ -z $idx ]] && (echo idx not provided ; exit 1)

ip_ext=VS_IP_${idx}_EXT
ip_ext=${!ip_ext}
ip_db=DB_IP_${idx}_INT
ip_db=${!ip_db}

cat $VECTOR_STORE_SCYLLADB_PASSWORD_FILE | ssh ubuntu@$ip_ext "cat > /home/ubuntu/vector-store-passwd"

# run vs in docker
ssh ubuntu@$ip_ext sudo docker run -d \
    --name vs \
    --net host \
    --ulimit nofile=104857600:104857600 \
    -v /home/ubuntu/vector-store-passwd:/opt/vector-store-passwd:ro \
    -e VECTOR_STORE_URI=0.0.0.0:6080 \
    -e VECTOR_STORE_SCYLLADB_URI=$ip_db:9042 \
    -e VECTOR_STORE_SCYLLADB_USERNAME=$VECTOR_STORE_SCYLLADB_USERNAME \
    -e VECTOR_STORE_SCYLLADB_PASSWORD_FILE=/opt/vector-store-passwd \
    $VECTOR_STORE_DOCKER_IMAGE
